# Generated by Django 3.1.7 on 2021-03-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210329_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='role',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
