# Generated by Django 3.1.7 on 2021-04-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='analysis',
            field=models.CharField(default='none', max_length=20000),
        ),
        migrations.AddField(
            model_name='appointment',
            name='medications',
            field=models.CharField(default='none', max_length=20000),
        ),
        migrations.AddField(
            model_name='appointment',
            name='problem',
            field=models.CharField(default='none', max_length=20000),
        ),
    ]
