# Generated by Django 3.1.6 on 2021-03-30 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor', serialize=False, to='auth.user')),
                ('years_of_experience', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('phone_number', models.CharField(default='01111111', max_length=15)),
                ('specialty', models.CharField(default='General', max_length=15)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(default='Doctor', max_length=10)),
                ('gender', models.CharField(default='M', max_length=1)),
            ],
        ),
    ]
