# Generated by Django 3.1.7 on 2021-03-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='role',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
