# Generated by Django 3.1.6 on 2021-04-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20210411_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
