# Generated by Django 3.1.7 on 2021-04-26 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctor_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(19), django.core.validators.MaxValueValidator(150)]),
        ),
    ]
